-- 코드를 입력하세요
-- 자동차 종류가 세단 or SUV
-- 2022-11-01 ~ 2022-11-30
-- 30일간의 대여금액이 50이상 ~ 200 미만
-- 자동차 ID, 종류 대여금액
# SELECT CRCC.CAR_ID, CRCC.CAR_TYPE, ROUND(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR CRCC
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
# ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
# WHERE CRCC.CAR_TYPE IN ('세단', 'SUV') AND
#     CRCDP.DURATION_TYPE = '30일 이상' AND
#     NOT EXISTS (
#         SELECT 1
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
#         WHERE CRCC.CAR_ID = CRCRH.CAR_ID AND
#             CRCRH.START_DATE < '2022-12-01' AND CRCRH.END_DATE > '2022-11-01'
#     )
#     AND ROUND(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100) >= 500000
#     AND ROUND(CRCC.DAILY_FEE * 30 * (100 - CRCDP.DISCOUNT_RATE) / 100) < 2000000
# ORDER BY FEE, CRCC.CAR_TYPE, CRCC.CAR_ID DESC;

SELECT
  C.CAR_ID,
  C.CAR_TYPE,
  ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND P.DURATION_TYPE = '30일 이상'
  AND NOT EXISTS (
    SELECT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE H.CAR_ID = C.CAR_ID
      AND H.END_DATE > '2022-11-01'
      AND H.START_DATE < '2022-12-01'
  )
  AND ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) >= 500000
  AND ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
    